language: python
python:
- '3.6'

dist: trusty

# Deployment Conditions
#   PRs, master and production will be automatically updated and rebuilt on git push.
#   Regular branches will not be built, they can be updated and commited at any time without disturbing PRs, master or staging.
if: |
  (branch IN (master, production, 1737-dev-buckets) AND type = push) OR (type = pull_request)

# We will need these services:
services:
- docker

sudo: required

# We need curl and jq
addons:
  apt:
    packages:
      - jq
      - curl

# We are going to install AWS Cli and source our helper scripts
before_install:
    - sudo pip install awscli
    - source ./.travis/aws-helper.sh

# Jobs
jobs:
  include:
  - stage: Build Docker Containers & Restarting containers on success
    script:
    - build_docker "latest"
    # Once built we release
    after_success:
    - restart_all_tasks
